### ISSUE TITLE
Incorrect project order

### ISSUE THREAD

**Issue by cmdecker95** [isaacpasc/isaacpasc.github.io#1]
First of all, great portfolio. I just found you by searching for a Netlify app and finding Dashify. Very impressed, especially with FoodBot.

In projects.html, you have the order mixed for PocketAI and Dashify. Either swap the chips (lines 46/47) or swap the .point divs.

Cheers 🍻

**Comment by isaacpasc** [comment]
Thanks so much for pointing this out! Just pushed a fix for the correct ordering.
